name: Homelab
ai_config:
  default_model:
    model: qwen3.8:27b
    provider: customai
  providers:
    customai:
      models:
        - qwen3.8:27b
        - qwen3.6:35b
        - qwen3.6:27b
        - qwen3.5:9b
        - qwen3-coder-next
        - qwen3-vl:32b
        - gemma4:26b
        - ornith1.5:35b
        - llama3.1:8b
      resource_path: f/ai/soclaas
error_handler: null
git_sync:
  repositories:
    - git_repo_resource_path: $res:f/git_sync/homelab_windmill
      group_by_folder: false
      settings:
        exclude_path: []
        extra_include_path: []
        include_path:
          - f/**
        include_type:
          - script
          - flow
          - app
          - folder
          - resource
          - variable
          - schedule
          - trigger
          - settings
      use_individual_branch: false
operator_settings:
  assets: true
  audit_logs: true
  folders: true
  groups: true
  resources: true
  runs: true
  schedules: true
  triggers: true
  variables: true
  workers: true
slack_oauth_client_id: null
slack_oauth_client_secret: null
success_handler: null
